version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/core_pbd"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/fishtank_ui"
    schedule:
      interval: "weekly"
